export const schema = {
  "@context": "https://schema.org",
  "@type": "Article",
  headline: "La création de site internet ! Trouves les 1001 astuces",
  description:
    "Création de site internet : 1001 astuces pratiques pour choisir vos outils, optimiser SEO et vitesse, sécuriser votre site et convertir davantage de visiteurs.",
  image: {
    "@type": "ImageObject",
    url: "https://www.guillaumeganne.com/images/creation-site-vitrine-angouleme.webp",
    width: 1200,
    height: 630,
  },
  author: {
    "@type": "Person",
    name: "Guillaume Ganne",
    url: "https://www.guillaumeganne.com",
    jobTitle: "Webdesigner",
    worksFor: {
      "@type": "Organization",
      name: "Guillaume Ganne - Webdesigner Angoulême",
    },
  },
  publisher: {
    "@type": "Organization",
    name: "Guillaume Ganne - Webdesigner Angoulême",
    url: "https://www.guillaumeganne.com",
    logo: {
      "@type": "ImageObject",
      url: "https://www.guillaumeganne.com/logo-guillaume-ganne-webdesigner-angouleme.svg",
    },
  },
  datePublished: "2024-01-15T10:00:00.000Z",
  dateModified: "2024-01-15T10:00:00.000Z",
  mainEntityOfPage: {
    "@type": "WebPage",
    "@id":
      "https://www.guillaumeganne.com/blog/creation-site-internet-1001-astuces",
  },
  articleSection: "Développement Web",
  keywords: [
    "création site internet",
    "développement web",
    "site vitrine",
    "e-commerce",
    "SEO",
    "optimisation site web",
    "hébergement web",
    "nom de domaine",
    "WordPress",
    "Wix",
    "Webflow",
    "Next.js",
    "référencement naturel",
    "conversion site web",
    "sécurité site internet",
    "vitesse site web",
    "responsive design",
    "UX design",
    "landing page",
    "portfolio web",
    "blog professionnel",
    "CMS",
    "framework web",
    "outils création site",
    "budget site internet",
    "coût site web",
    "maintenance site",
    "RGPD",
    "certificat SSL",
    "moteurs de recherche",
  ],
  wordCount: 3500,
  timeRequired: "PT15M",
  inLanguage: "fr-FR",
  isAccessibleForFree: true,
  breadcrumb: {
    "@type": "BreadcrumbList",
    itemListElement: [
      {
        "@type": "ListItem",
        position: 1,
        name: "Accueil",
        item: "https://www.guillaumeganne.com",
      },
      {
        "@type": "ListItem",
        position: 2,
        name: "Blog",
        item: "https://www.guillaumeganne.com/blog",
      },
      {
        "@type": "ListItem",
        position: 3,
        name: "Création site internet : 1001 astuces",
        item: "https://www.guillaumeganne.com/blog/creation-site-internet-1001-astuces",
      },
    ],
  },
  potentialAction: {
    "@type": "ReadAction",
    target:
      "https://www.guillaumeganne.com/blog/creation-site-internet-1001-astuces",
  },
};
